# Preface {.unnumbered}

Preregistration is an important research standard to guard against questionable research practices and protect the integrity of statistical inferences. But there are parts of a new study that can be difficult or impossible to define in advance, particularly when both exploratory data analysis (EDA) and confirmatory data analysis (CDA) are needed to advance the research program.

In this tutorial, we will discuss how to use preregistration to help you plan both exploratory and confirmatory work, addressing two common sources of frustration for researchers developing new projects: model specification and sample size estimation.

In particular, we will showcase the value of exploratory work for hypothesis generation as part of the iterative scientific process. Exploratory studies and analyses help researchers refine and specify their research questions and statistical hypotheses, enabling them to properly design, preregister, and conduct confirmatory studies and ultimately build stronger theories of scientific understanding.
