# Research Processes {.sec-research_processes}

### Explore, Hypothesize, Infer, (Dis)Confirm, Repeat.

Exploratory and confirmatory analyses constitute two overarching objectives of research inquiry. However, there are several steps in the iterative research process that connect the exploratory and confirmatory parts of the scientific process.

The key steps in this process revolve around hypotheses: *hypothesis generation* and *hypothesis testing.*

In the following section, we will review the exploratory steps and the confirmatory steps using some examples of each type of question and its corresponding analyses.

The goal is *not* to partition all research into either exploratory (hypothesis-generating) research or confirmatory (hypothesis-testing) research---such a task is likely not even possible [@fife2022a; @jacobucci2022]. Instead, we will review strategies for identifying and differentiating the exploratory and confirmatory *objectives* within a research program, bearing in mind that most research programs will contain both exploratory and confirmatory lines of inquiry at various stages.